---
- name: Provision AMI
  hosts: all
  vars:
    additional_ntp_servers: ["169.254.169.123"]
    vault_version: "1.5.4"
    vault_ui_enable: "true"
    vault_module_url: "https://github.com/hashicorp/terraform-aws-vault.git"
    vault_module_version: "v0.11.3"
    consul_module_version: "v0.3.5"
    consul_version: "1.4.0"
    consul_enable_syslog: true
    tls_cert_file_src: "{{ playbook_dir }}/cert/cert.pem"
    encrypted_tls_key_file_src: "{{ playbook_dir }}/cert/encrypted_vault.key"
    encrypted_aes_key_src: "{{ playbook_dir }}/cert/aes.key"
    cli_json_src: "{{ playbook_dir }}/cert/cli.json"
    td_agent_config_file: ""
    td_agent_config_vars_file: ""
    td_agent_config_app_vars_file: ""
    td_agent_config_dest_file: "/etc/td-agent/td-agent.conf"
    ca_certificate: ""
    consul_host: ""
    consul_port: 443
    consul_scheme: https
    consul_token: ""
    consul_integration_prefix: "terraform/"
    timezone: "Asia/Singapore"
  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      upgrade: yes
      update_cache: yes
    become: yes
  - name: Install CA Certificate
    include_tasks: "{{ playbook_dir }}/../../../../tasks/include_role_checked.yml"
    vars:
      role: "{{ playbook_dir }}/../../../../roles/ansible-ca-store"
      certificate: "{{ ca_certificate }}"
      certificate_rename: "ca.crt"
    become: yes
    when: ca_certificate != ""
  - name: Install Vault PKI CA Certificate
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/vault-pki"
  - name: Install chrony
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/chrony"
  - name: Install td-agent
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/td-agent"
    vars:
      config_file: "{{ td_agent_config_file }}"
      config_vars_file: "{{ td_agent_config_vars_file }}"
      config_app_vars_file: "{{ td_agent_config_app_vars_file }}"
      config_dest_file: "{{ td_agent_config_dest_file }}"
  - name: Install Telegraf
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/telegraf"
  - name: Install Consul
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/consul"
    vars:
      consul_client_address: "127.0.0.1 169.254.1.1"
  - name: Install Consul-Template
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/install-consul-template"
  - name: Install Vault
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/vault"
  - name: Install Vault SSH Configuration Script
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/install-ssh-script"
  - name: Set default timezone
    include_role:
      name: "{{ playbook_dir }}/../../../../roles/timezone"
